# Generated by Django 4.2.5 on 2023-10-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_alter_post_options_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('browser', models.CharField(max_length=200, verbose_name='браузер')),
                ('os', models.CharField(max_length=200, verbose_name='операционная система')),
                ('is_bot', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch_capable', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='posts.post')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
