# Generated by Django 4.2.7 on 2023-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockListIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('block_list', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IP в блок листе',
                'verbose_name_plural': 'IP в блок листах',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='postscounter',
            name='block_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postscounter',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postscounter',
            name='ref_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='реферальная url'),
        ),
    ]
