version: "3.11"

services:
  redis:
    image: redis:alpine
    container_name: todo_redis
    restart: always

  web:
      build:
        context: .
        dockerfile: LocalDockerfile
      container_name: todo_django
      restart: always
      command: bash -c "python3 todo/manage.py migrate && python3 todo/manage.py set_webhook && python3 todo/manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      env_file:
        - ./.env
  celery:
    build:
      context: .
      dockerfile: LocalDockerfile
    container_name: todo_celery
    restart: always
    command: bash -c "cd todo && celery -A todo worker --loglevel=INFO"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
  celery-beat:
    build:
      context: .
      dockerfile: LocalDockerfile
    container_name: todo_beat
    restart: always
    command: bash -c "cd todo && celery -A todo beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web
