version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - /home/exp-ext/pgdata/todo/:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:7-alpine
    container_name: todo_redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    container_name: todo_django
    restart: always
    command: ./web_entrypoint.sh
    volumes:
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - static_volume:/app/web/static
      - media_volume:/app/web/media
    ports:
      - 8080:80
    depends_on:
      - web
    environment:
      - name=value

  celery:
    build:
      context: .
    container_name: todo_celery
    restart: always
    command: bash -c "cd todo && celery -A todo worker --loglevel=INFO"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
      - db

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: todo_beat
    restart: always
    command: bash -c "cd todo && celery -A todo beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - celery
      - web
      - db

volumes:
  static_volume:
  media_volume:
