version: '3.9'

services:
  db:
    image: postgres:13.10-alpine
    container_name: todo_db
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todo_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - 8090:80
    volumes:
      - pgadmin_data_todo:/var/lib/pgadmin/

  redis:
    image: redis:latest
    container_name: todo_redis
    restart: always
    command: >
          --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../todo/
      dockerfile: Dockerfile
    container_name: todo_celery
    restart: always
    command: bash -c "celery -A todo worker --loglevel=INFO"
    volumes:      
      - ../backup:/app/backup/:rw
      - ../todo/:/app/:rw
      - cache_pip_volume:/root/.cache/pip/:rw
      - cache_apt_volume:/var/cache/apt/archives/:rw
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery-beat:
    build:
      context: ../todo/
      dockerfile: Dockerfile 
    container_name: todo_beat
    restart: always
    command: bash -c "celery -A todo beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler"
    volumes:
      - ../backup:/app/backup/:rw
      - ../todo/:/app/:rw
      - cache_pip_volume:/root/.cache/pip/:rw
      - cache_apt_volume:/var/cache/apt/archives/:rw
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - celery

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: todo_whisper
    ports:
      - "9009:9000"
    environment:
      - ASR_MODEL=small
      - ASR_ENGINE=openai_whisper

  nginx:
    image: nginx:latest
    container_name: todo_nginx
    volumes:
      - ./nginx/default_dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    network_mode: host

volumes:
  backup_volume:
  postgresql_volume:
  cache_pip_volume:
  cache_apt_volume:
  pgadmin_data_todo:
