# Generated by Django 4.1.5 on 2023-02-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание группы'),
        ),
    ]
