# Generated by Django 4.2.5 on 2023-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_tg_id_user_validation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
