# Generated by Django 4.1.6 on 2023-02-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmailing',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mailing', to='users.group'),
        ),
    ]
