# Generated by Django 4.2.5 on 2023-10-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_validation_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
