# Generated by Django 4.2.5 on 2023-10-28 19:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
