# Generated by Django 4.2.5 on 2023-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number_alter_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
