# Generated by Django 4.1.4 on 2022-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(through='users.GroupConnections', to='users.group'),
        ),
    ]
