# Generated by Django 4.1.3 on 2022-11-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время мероприятия'),
        ),
    ]
