# Generated by Django 4.1.4 on 2023-01-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_group'),
        ('tasks', '0003_remove_task_user_date_alter_task_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Если выбрать группу, то оповещение будет в ней.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.group', verbose_name='Группа'),
        ),
    ]
