# Generated by Django 4.2.11 on 2024-03-12 17:23

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import sorl.thumbnail.fields
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_blocked_bot'),
        ('tasks', '0003_task_image_alter_task_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('server_datetime',), 'verbose_name': 'напоминание', 'verbose_name_plural': 'напоминания'},
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, help_text='если выбрать группу, то оповещение будет в ней', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='приоритетной для напоминания считается именно эта картинка', upload_to=tasks.models.custom_uuid_filename, verbose_name='ваша картинка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='it_birthday',
            field=models.BooleanField(verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='picture_link',
            field=models.CharField(blank=True, help_text='ссылка в формате https://domen.ru/fantasy.jpg', max_length=200, verbose_name='ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(verbose_name='время срабатывания оповещения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='remind_min',
            field=models.IntegerField(default=120, help_text='оповестить за ... минут до наступления события', verbose_name='оповестить за ... минут'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_period',
            field=models.CharField(choices=[('N', 'Никогда'), ('D', 'Каждый день'), ('W', 'Каждую неделю'), ('M', 'Каждый месяц'), ('Y', 'Каждый год')], default='N', help_text='выберите период повторения напоминания', max_length=1, verbose_name='периодичность напоминания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='введите текст напоминания', verbose_name='текст напоминания'),
        ),
    ]
