# Generated by Django 4.1.5 on 2023-01-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture_link',
            field=models.CharField(blank=True, help_text='Ссылка в формате https://domen.ru/fantasy.jpg.', max_length=200, verbose_name='Ссылка на картинку'),
        ),
    ]
