# Generated by Django 4.1.5 on 2023-01-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_picture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture_link',
            field=models.CharField(blank=True, help_text='Ссылка в формате https://domen.ru/fantasy.jpg', max_length=200, verbose_name='Ссылка на картинку'),
        ),
    ]
