# Generated by Django 4.1.5 on 2023-01-30 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_alter_task_picture_link'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='celebratoryfriend',
            name='unique_follower',
        ),
        migrations.AlterField(
            model_name='celebratoryfriend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebratoryfriend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='celebratoryfriend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_following_of_friend'),
        ),
    ]
