# Generated by Django 4.2.7 on 2024-02-05 12:47

from django.db import migrations, models
import django_ckeditor_5.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='advertising/', verbose_name='картинка')),
                ('reference', models.CharField(max_length=200, verbose_name='партнерская ссылка')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='слоган банера')),
            ],
            options={
                'verbose_name': 'мой банер на сайте',
                'verbose_name_plural': 'мои банере на сайте',
            },
        ),
    ]
