# Generated by Django 4.2.7 on 2023-12-02 09:15

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='описание')),
                ('script', models.TextField(verbose_name='скрипт для отображения в станице')),
                ('form', models.CharField(choices=[('l', 'линейная форма'), ('s', 'квадратная форма')], default='l', max_length=1, verbose_name='тип виджета')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='partnerbanner',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='слоган банера'),
        ),
        migrations.AlterField(
            model_name='telegrammailing',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='слоган банера'),
        ),
    ]
