# Generated by Django 4.2.5 on 2023-10-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerbanner',
            options={'verbose_name': 'банер на сайте', 'verbose_name_plural': 'банеры на сайте'},
        ),
    ]
