# Generated by Django 4.2.7 on 2024-02-06 08:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_mybanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybanner',
            options={'verbose_name': 'мой банер на сайте', 'verbose_name_plural': 'мои банеры на сайте'},
        ),
        migrations.AddField(
            model_name='mybanner',
            name='mobile_text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='слоган банера для мобильной версии'),
            preserve_default=False,
        ),
    ]
