# Generated by Django 4.2.7 on 2023-12-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_advertisementwidget_alter_partnerbanner_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementwidget',
            name='advertiser',
            field=models.CharField(default=1, max_length=100, verbose_name='рекламодатель'),
            preserve_default=False,
        ),
    ]
