# Generated by Django 4.1.7 on 2023-02-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historyai',
            unique_together=set(),
        ),
    ]
