# Generated by Django 4.2.5 on 2023-11-12 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telbot', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyai',
            name='room_group_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='WEB чат'),
        ),
        migrations.AlterField(
            model_name='historyai',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_ai', to=settings.AUTH_USER_MODEL),
        ),
    ]
