# Generated by Django 4.1.7 on 2023-04-04 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telbot', '0002_alter_historyai_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('question', models.TextField(verbose_name='Запрос')),
                ('answer', models.JSONField(verbose_name='Ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_dalle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История запросов к Dalle',
                'verbose_name_plural': 'История запросов к Dalle',
                'ordering': ('created_at',),
            },
        ),
    ]
