# Generated by Django 4.2.11 on 2024-03-12 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telbot', '0003_gptmodels_usergptmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('question_tokens', models.PositiveIntegerField(null=True)),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_tokens', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_history_ai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История запросов на преобразования напоминания к ИИ',
                'verbose_name_plural': 'История запросов на преобразования напоминания к ИИ',
                'ordering': ('created_at',),
            },
        ),
    ]
