# Generated by Django 4.2.10 on 2024-03-04 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telbot', '0003_gptmodels_usergptmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergptmodels',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
