# Generated by Django 4.1.7 on 2023-04-05 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telbot', '0003_historydalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryWhisper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_id', models.CharField(max_length=64, verbose_name='Id файла')),
                ('transcription', models.TextField(verbose_name='Аудиотранскрибция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_whisper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История запросов к Whisper',
                'verbose_name_plural': 'История запросов к Whisper',
                'ordering': ('created_at',),
            },
        ),
    ]
