# Generated by Django 4.2.11 on 2024-03-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0004_reminderai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historywhisper',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoryTranslation',
        ),
        migrations.DeleteModel(
            name='HistoryWhisper',
        ),
    ]
