# Generated by Django 4.2.11 on 2024-03-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0005_remove_historywhisper_user_delete_historytranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptmodels',
            name='context_window',
            field=models.IntegerField(verbose_name='окно количества токенов для передачи истории в запросе'),
        ),
        migrations.AlterField(
            model_name='gptmodels',
            name='max_request_token',
            field=models.IntegerField(verbose_name='максимальное количество токенов в запросе'),
        ),
    ]
