# Generated by Django 4.1.7 on 2023-04-09 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telbot', '0005_alter_historywhisper_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('translation', models.TextField(verbose_name='Перевод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_translation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История запросов для перевода',
                'verbose_name_plural': 'История запросов для перевода',
                'ordering': ('created_at',),
            },
        ),
    ]
