# Generated by Django 4.1.7 on 2023-05-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telbot', '0006_historytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyai',
            name='answer_tokens',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historyai',
            name='question_tokens',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
