# Generated by Django 4.1.7 on 2023-06-08 13:45

from django.db import migrations, models
import django_ckeditor_5.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.TextField(help_text='Введите текст комментария', verbose_name='Текст комментария')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок поста')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст поста')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='posts/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-created_at',),
            },
        ),
    ]
