# Generated by Django 4.2.5 on 2023-11-15 08:34

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.TextField(help_text='введите текст комментария', verbose_name='текст комментария')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=80, verbose_name='заголовок поста')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='текст поста')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='posts/', verbose_name='картинка')),
                ('moderation', models.CharField(choices=[('WT', 'ОЖИДАЕТ ПОДТВЕРЖДЕНИЯ'), ('PS', 'МОДЕРАЦИЯ ПРОЙДЕНА'), ('NM', 'МОДЕРАЦИЯ НЕ ПРОЙДЕНА')], default='WT', max_length=2, verbose_name='модерация заметки')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='тэг поста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
        migrations.CreateModel(
            name='PostContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('anchor', models.CharField(max_length=80, verbose_name='заголовок/глава/раздел')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='posts.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'оглавление',
                'verbose_name_plural': 'оглавления',
            },
        ),
    ]
