# Generated by Django 4.2.7 on 2023-12-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_id_06b5f3_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='slug поста'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'),
        ),
    ]
