# Generated by Django 4.2.7 on 2023-11-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcontents',
            options={'ordering': ('id',), 'verbose_name': 'оглавление', 'verbose_name_plural': 'оглавления'},
        ),
    ]
