# Generated by Django 4.2.7 on 2023-12-23 11:53

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_posts_post_id_06b5f3_idx_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttags',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='tags/', verbose_name='картинка'),
        ),
    ]
