# Generated by Django 4.2.7 on 2023-12-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postcontents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='anchor',
            field=models.CharField(max_length=250, verbose_name='заголовок/глава/раздел'),
        ),
    ]
