# Generated by Django 4.2.5 on 2023-11-09 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posttags_post_passed_moderation_postcontents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='anchor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='якорь'),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='posts.post', verbose_name='пост'),
        ),
    ]
