# Generated by Django 4.2.5 on 2023-11-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postcontents_anchor_alter_postcontents_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontents',
            name='desc',
        ),
    ]
