# Generated by Django 4.2.7 on 2024-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='короткое описание'),
        ),
    ]
