# Generated by Django 4.2.5 on 2023-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postcontents_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='passed_moderation',
            field=models.CharField(choices=[('WT', 'ОЖИДАЕТ ПОДТВЕРЖДЕНИЯ'), ('PS', 'МОДЕРАЦИЯ ПРОЙДЕНА'), ('NM', 'МОДЕРАЦИЯ НЕ ПРОЙДЕНА')], default='WT', max_length=3, verbose_name='модерация пройдена'),
        ),
    ]
