# Generated by Django 4.2.7 on 2024-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='короткое описание поста'),
        ),
    ]
