# Generated by Django 4.2.5 on 2023-11-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_passed_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='passed_moderation',
        ),
        migrations.AddField(
            model_name='post',
            name='moderation',
            field=models.CharField(choices=[('WT', 'ОЖИДАЕТ ПОДТВЕРЖДЕНИЯ'), ('PS', 'МОДЕРАЦИЯ ПРОЙДЕНА'), ('NM', 'МОДЕРАЦИЯ НЕ ПРОЙДЕНА')], default='WT', max_length=2, verbose_name='модерация заметки'),
        ),
    ]
