# Generated by Django 4.2.5 on 2023-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_passed_moderation_post_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontents',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80, verbose_name='заголовок поста'),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='anchor',
            field=models.CharField(default=1, max_length=80, verbose_name='заголовок/глава/раздел'),
            preserve_default=False,
        ),
    ]
