version: '3.9'

services:

  nginx:
    image: nginx:latest
    container_name: main_nginx
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/lib/letsencrypt/:rw
      - static_volume:/var/html/static/:ro
      - media_volume:/var/html/media/:ro
      - type: tmpfs
        target: /var/cache/nginx/minio_cache
        tmpfs:
          size: 1000000000
    ports:
      - '80:80'
      - '443:443'
    network_mode: host

  certbot:
    image: certbot/certbot
    container_name: main_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/lib/letsencrypt/:rw
    entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 48h & wait $${!}; done;"'
    depends_on:
      - nginx

  minio:
    restart: always
    image: minio/minio:latest
    container_name: main_minio
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9090:9001'
    volumes:
      - upload_minio_volume:/data
    env_file:
      - ./.env
    depends_on:
      - nginx

  createbuckets:
    image: minio/mc
    container_name: main_createbuckets
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} --api S3v4;
      /usr/bin/mc mb minio/${AWS_STATIC_BUCKET_NAME};
      /usr/bin/mc mb minio/${AWS_MEDIA_BUCKET_NAME};
      /usr/bin/mc mb minio/${AWS_BACKUP_BUCKET_NAME};
      exit 0;
      "
    volumes:
      - upload_minio_volume:/data
      - ./:/ro
    env_file:
      - ./.env
    depends_on:
      - minio

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: main_whisper
    ports:
      - "9009:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper

volumes:
  upload_minio_volume:
  media_volume:
    external: true
  static_volume:
    external: true
