version: '3.9'

services:

  nginx:
    image: nginx:latest
    container_name: main_nginx
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/lib/letsencrypt/:rw
    ports:
      - '80:80'
      - '443:443'
    network_mode: host

  certbot:
    image: certbot/certbot
    container_name: main_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/lib/letsencrypt/:rw
    entrypoint: '/bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 48h & wait $${!}; done;"'
    depends_on:
      - nginx

  minio:
    restart: always
    image: bitnami/minio:latest
    container_name: main_minio
    ports:
      - '9050:9000'
      - '9001:9001'
    volumes:
      - minio_volume:/data
    env_file:
      - ./.env
    depends_on:
      - nginx

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: main_whisper
    ports:
      - "10000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    depends_on:
      - nginx

volumes:
  minio_volume:
